name: groupbin
channels:
  - defaults
dependencies:
  - python
  - pip
  - pip:
      - flask
      - flask-sqlalchemy
      - flask-login
      - flask-session
      - werkzeug
      - python-dotenv
      - flask-cors
      - gunicorn
      - pycryptodome
      - python-multipart
      - tqdm
      - flask-wtf
